version: "3.9"

services:
    mldictionary_api:
        build:
            context: .
        container_name: mldictionary_api
        ports:
            - 8088:8088
        volumes:
            - .:/opt/api
        networks:
            - mldictionary_api_network
        depends_on:
            - redis

    redis:
        image: redis
        volumes:
            - mldictionary_api_volume:/data
        ports:
            - 6379:6379
        container_name: mldictionary_api_redis
        command: redis-server --requirepass default
        networks:
            - mldictionary_api_network

volumes:
    mldictionary_api_volume:

networks:
    mldictionary_api_network:
        driver: "bridge"